version: '3'

services:
  maintenance-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:5000"  # Using port 9000 for host
    volumes:
      - ./instance:/app/instance
      - ./backups:/app/backups
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    container_name: amrs-maintenance-tracker
    # Add healthcheck to detect problems early
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

# Define network to isolate container communication
networks:
  app-network:
    driver: bridge
