version: '3'

services:
  app:
    build: ./server
    ports:
      - "$CONTAINER_PORT:$CONTAINER_PORT"
    environment:
      - DATABASE_URL=sqlite:////app/data/app.db
      - SECRET_KEY=secure_$(date +%s)_key
      - DEBUG=True  # Enable debugging temporarily to help identify issues
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - PORT=$CONTAINER_PORT
      # Remove SERVER_NAME to avoid routing issues initially
      # - SERVER_NAME=$DDNS_HOSTNAME
      - PREFERRED_URL_SCHEME=https
    volumes:
      - $DATA_DIR:/app/data
    restart: "unless-stopped"
    container_name: amrs-maintenance-tracker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:$CONTAINER_PORT/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    ports:
      - "$EXTERNAL_PORT_HTTP:80"
      - "$EXTERNAL_PORT_HTTPS:443"
    volumes:
      - $DATA_DIR/nginx/conf.d:/etc/nginx/conf.d
      - $DATA_DIR/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

networks:
  default:
    name: amrs_network
    external: true  # Mark the network as external
