version: '3'

services:
  app:
    build: ./server
    ports:
      - "9000:9000"
    environment:
      - DATABASE_URL=sqlite:///data/app.db
      - SECRET_KEY=your_secure_production_key_here
      - DEBUG=False  # Set to False in production
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
      - SERVER_NAME=your-ddns-hostname.synology.me  # Your DDNS hostname
      - PREFERRED_URL_SCHEME=https
    volumes:
      - /volume1/docker/data:/app/data  # Change this line to point to an existing directory on your Synology
    restart: "unless-stopped"  # Better for production than "on-failure"
    container_name: amrs-maintenance-tracker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Use different ports for Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"   # Map container port 80 to host port 8080
      - "8443:443"  # Map container port 443 to host port 8443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  # Use local directory for certificates
    depends_on:
      - app
    restart: unless-stopped

networks:
  default:
    driver: bridge
