version: '3'

services:
  maintenance-app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - ./backups:/app/backups
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
