version: '3'

services:
  maintenance-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:5000"  # Using port 9000 for host
    volumes:
      - ./instance:/app/instance
      - ./backups:/app/backups
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - SECRET_KEY=change_this_to_a_secure_random_string
      # Comment out SERVER_NAME if you're using a reverse proxy or don't need domain-specific routing
      # - SERVER_NAME=your.domain.com 
    container_name: amrs-maintenance-tracker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
