services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x startup.sh
    startCommand: ./startup.sh
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      # The SERVER_NAME should match your Render URL - critical fix for routing
      - key: SERVER_NAME
        sync: false # Let this be manually set to match your Render URL
      - key: PREFERRED_URL_SCHEME
        value: "https"
      # The rest of the existing environment variables
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
    disk:
      name: maintenance-data
      mountPath: /var/data
      sizeGB: 1
