services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash ./onstart.sh
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: PORT
        fromService:
          name: maintenance-tracker
          type: web
          envVarKey: RENDER_PORT
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
