services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: |
      echo "Creating custom requirements file for Render deployment..."
      cat > render_requirements.txt << EOL
      # Core dependencies with fixed versions to avoid conflicts
      Flask==2.2.5
      Werkzeug==2.2.3
      click==8.1.3
      itsdangerous==2.1.2
      Jinja2==3.1.2
      MarkupSafe==2.1.2
      SQLAlchemy==2.0.12
      flask-sqlalchemy==3.0.3
      flask-login==0.6.2
      flask-mail==0.9.1
      flask-cors==4.0.0
      gunicorn==21.2.0
      pandas==2.0.3
      numpy==1.24.3
      # Add any other specific requirements your application needs
      EOL
      
      echo "Installing custom requirements..."
      pip install --upgrade pip
      pip install -r render_requirements.txt
      
      # In case of failure, try installing critical packages individually
      if [ $? -ne 0 ]; then
        echo "Attempting alternative installation method..."
        pip install Flask==2.2.5 Werkzeug==2.2.3 --no-deps
        pip install gunicorn==21.2.0 --no-deps
        pip install flask-login==0.6.2 flask-sqlalchemy==3.0.3 --no-deps
        pip install SQLAlchemy==2.0.12 --no-deps
      fi
      
      echo "Dependencies installed successfully"
    startCommand: |
      if [ -f "startup.sh" ]; then
        echo "Running startup script..."
        chmod +x startup.sh
        ./startup.sh
      else
        echo "Creating necessary directories..."
        mkdir -p /var/data/db
        mkdir -p /var/data/backups
        mkdir -p /var/data/uploads
        chmod -R 755 /var/data
      fi
      echo "Starting application..."
      gunicorn wsgi:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: maintenance-tracker
          envVarKey: RENDER_PORT
      - key: DATA_DIR
        value: /var/data
    disk:
      sizeGB: 2
      mountPath: /var/data
      name: maintenance-data
