services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: |
      echo "Installing dependencies directly from requirements.txt..."
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gunicorn==21.2.0
      
      # Create the adapter file that Render is expecting
      echo "Creating app.py adapter for Render..."
      if [ -f "app_render.py" ]; then
        cp app_render.py app.py
        echo "app_render.py copied to app.py"
      else
        echo "from wsgi import app" > app.py
        echo "Basic adapter created as app.py"
      fi
    startCommand: gunicorn app:app
    healthCheckPath: /health
    healthCheckTimeout: 5s
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: maintenance-tracker
          envVarKey: RENDER_PORT
      - key: DATA_DIR
        value: /var/data
      - key: DATABASE_URL
        value: sqlite:///var/data/db/maintenance.db
      - key: LOG_LEVEL
        value: INFO
    disk:
      sizeGB: 2
      mountPath: /var/data
      name: maintenance-data
