services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./startup.sh
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: maintenance-tracker
          envVarKey: RENDER_EXTERNAL_URL
    disk:
      name: maintenance-data
      mountPath: /var/data
      sizeGB: 1
    healthCheckPath: /health
    # Auto deploys are off so we avoid deployments interrupting users
    autoDeploy: false
