services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: |
      pip install --upgrade pip
      # Install gunicorn first
      pip install gunicorn==21.2.0
      # Then install other dependencies
      pip install -r requirements.txt
      # Create directories needed
      mkdir -p /var/data/db /var/data/backups /var/data/uploads
      chmod -R 755 /var/data
    # Let Render use the Procfile
    # Don't specify startCommand so Render will use Procfile
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: maintenance-tracker
          envVarKey: RENDER_PORT
      - key: DATA_DIR
        value: /var/data
      - key: DATABASE_URL
        value: sqlite:///var/data/db/maintenance.db
      - key: LOG_LEVEL
        value: INFO
      - key: PATH
        value: /opt/render/project/python3/bin:/opt/render/project/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    disk:
      sizeGB: 2
      mountPath: /var/data
      name: maintenance-data
