services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      if python -c "import app" 2>/dev/null; then
        echo "Starting main app..."
        gunicorn app:app --workers=1 --timeout=120 --capture-output --log-level=debug
      else
        echo "Main app import failed! Starting minimal app..."
        gunicorn minimal_app:application --workers=1 --timeout=120 --capture-output --log-level=debug
      fi
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
    disk:
      name: maintenance-data
      mountPath: /var/data
      sizeGB: 1
    healthCheckPath: /healthz
