services:
  - type: web
    name: amrs-maintenance
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install gunicorn==21.2.0
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: app.py
