services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      # Add this environment variable to set a custom default admin password
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: maintenance-tracker
          envVarKey: RENDER_PORT
    disk:
      name: maintenance-data
      mountPath: /var/data
      sizeGB: 2  # Increased to 2GB for more storage space
