services:
  - type: web
    name: maintenance-tracker
    env: python
    buildCommand: |
      echo "Installing dependencies manually to avoid conflicts..."
      pip install --upgrade pip
      
      # First install core packages with specific versions
      pip install Werkzeug==2.2.3
      pip install Flask==2.2.5
      pip install SQLAlchemy==2.0.12
      
      # Then install Flask extensions
      pip install flask-sqlalchemy==3.0.3
      pip install flask-login==0.6.2
      pip install flask-mail==0.9.1
      pip install flask-cors==4.0.0
      
      # Install other critical dependencies
      pip install gunicorn==21.2.0
      pip install Jinja2==3.1.2
      pip install MarkupSafe==2.1.2
      pip install click==8.1.3
      pip install itsdangerous==2.1.2
      
      # Install data processing libraries
      pip install pandas==2.0.3
      pip install numpy==1.24.3
      pip install pytz==2023.3
      pip install requests==2.31.0
      
      # Install utility packages
      pip install python-dotenv==1.0.0
      
      echo "Dependencies installed successfully"
    startCommand: |
      # Set up directories
      echo "Setting up directory structure..."
      mkdir -p /var/data/db
      mkdir -p /var/data/backups
      mkdir -p /var/data/uploads
      chmod -R 755 /var/data
      
      # Initialize database if needed
      echo "Checking database..."
      if [ ! -f "/var/data/db/maintenance.db" ]; then
        echo "Database not found, initializing..."
        python -c "from models import db; from app import app; with app.app_context(): db.create_all()"
      fi
      
      # Start the application
      echo "Starting application..."
      gunicorn wsgi:app
    healthCheckPath: /health
    healthCheckTimeout: 5s
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: RENDER
        value: "true"
      - key: FLASK_DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: PORT
        fromService:
          type: web
          name: maintenance-tracker
          envVarKey: RENDER_PORT
      - key: DATA_DIR
        value: /var/data
      - key: DATABASE_URL
        value: sqlite:///var/data/db/maintenance.db
      - key: LOG_LEVEL
        value: INFO
    disk:
      sizeGB: 2
      mountPath: /var/data
      name: maintenance-data
