import React from 'react'
import { Card, Table, Typography, Space, Tag, Divider } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import '../../styles/reports.css'

const { Title, Text, Paragraph } = Typography

interface MaintenanceRecord {
  id: number
  date: string
  machine: string
  task: string
  technician: string
  duration: string
  status: 'completed' | 'pending' | 'overdue'
  notes: string
}

interface ReportProps {
  startDate: string
  endDate: string
  site?: string
  data: MaintenanceRecord[]
}

/**
 * Option A: Minimalist Table Layout
 * Clean, professional table with clear hierarchy
 * Best for: Monthly reports, management reviews
 */
const MaintenanceReportOptionA: React.FC<ReportProps> = ({ 
  startDate, 
  endDate, 
  site = 'All Sites',
  data 
}) => {
  const columns: ColumnsType<MaintenanceRecord> = [
    {
      title: 'Date',
      dataIndex: 'date',
      key: 'date',
      width: 100,
    },
    {
      title: 'Machine',
      dataIndex: 'machine',
      key: 'machine',
      width: 150,
    },
    {
      title: 'Task',
      dataIndex: 'task',
      key: 'task',
      width: 200,
    },
    {
      title: 'Technician',
      dataIndex: 'technician',
      key: 'technician',
      width: 120,
    },
    {
      title: 'Duration',
      dataIndex: 'duration',
      key: 'duration',
      width: 80,
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      width: 100,
      render: (status: string) => {
        const colors = {
          completed: 'green',
          pending: 'blue',
          overdue: 'red',
        }
        return <Tag color={colors[status as keyof typeof colors]}>{status.toUpperCase()}</Tag>
      },
    },
  ]

  const completedCount = data.filter(r => r.status === 'completed').length
  const pendingCount = data.filter(r => r.status === 'pending').length
  const overdueCount = data.filter(r => r.status === 'overdue').length

  return (
    <div className="report-container option-a">
      {/* Header */}
      <div className="report-header">
        <div className="company-branding">
          <Title level={2}>AMRS Maintenance Tracker</Title>
          <Text type="secondary">Preventative Maintenance Report</Text>
        </div>
        <div className="report-meta">
          <Space direction="vertical" size="small">
            <Text><strong>Report Period:</strong> {startDate} to {endDate}</Text>
            <Text><strong>Site:</strong> {site}</Text>
            <Text><strong>Generated:</strong> {new Date().toLocaleString()}</Text>
          </Space>
        </div>
      </div>

      <Divider />

      {/* Summary Statistics */}
      <div className="report-summary">
        <Title level={4}>Summary</Title>
        <Space size="large">
          <Card size="small" style={{ minWidth: 150 }}>
            <Statistic title="Total Tasks" value={data.length} />
          </Card>
          <Card size="small" style={{ minWidth: 150 }}>
            <Statistic 
              title="Completed" 
              value={completedCount} 
              valueStyle={{ color: '#52c41a' }}
            />
          </Card>
          <Card size="small" style={{ minWidth: 150 }}>
            <Statistic 
              title="Pending" 
              value={pendingCount} 
              valueStyle={{ color: '#1890ff' }}
            />
          </Card>
          <Card size="small" style={{ minWidth: 150 }}>
            <Statistic 
              title="Overdue" 
              value={overdueCount} 
              valueStyle={{ color: '#ff4d4f' }}
            />
          </Card>
        </Space>
      </div>

      <Divider />

      {/* Main Table */}
      <div className="report-table">
        <Title level={4}>Maintenance Records</Title>
        <Table
          columns={columns}
          dataSource={data}
          pagination={false}
          size="small"
          bordered
          className="print-friendly-table"
        />
      </div>

      {/* Footer */}
      <div className="report-footer">
        <Divider />
        <Space direction="vertical" size="small">
          <Text type="secondary">
            This report contains {data.length} maintenance records for the period {startDate} to {endDate}.
          </Text>
          <Text type="secondary">
            Generated by AMRS Maintenance Tracker on {new Date().toLocaleDateString()}
          </Text>
        </Space>
      </div>
    </div>
  )
}

// Statistic component (simplified inline version)
const Statistic: React.FC<{ title: string; value: number; valueStyle?: React.CSSProperties }> = ({
  title,
  value,
  valueStyle,
}) => (
  <div style={{ textAlign: 'center' }}>
    <div style={{ fontSize: 12, color: '#8c8c8c', marginBottom: 4 }}>{title}</div>
    <div style={{ fontSize: 24, fontWeight: 600, ...valueStyle }}>{value}</div>
  </div>
)

export default MaintenanceReportOptionA
